# Generated by Django 4.2.4 on 2023-09-20 22:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=False)),
            ],
            options={"ordering": ["-created_date"],},
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(default="teacher.png", upload_to="trainer"),
                ),
                ("twitter", models.CharField(default="#", max_length=255)),
                ("facebook", models.CharField(default="#", max_length=255)),
                ("instagram", models.CharField(default="#", max_length=255)),
                ("linkedin", models.CharField(default="#", max_length=255)),
                ("status", models.BooleanField(default=False)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("skills", models.ManyToManyField(to="course.skills")),
            ],
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "which_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.comment"
                    ),
                ),
            ],
            options={"ordering": ["-created_date"],},
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("content", models.TextField(max_length=1000)),
                ("price", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="courses"),
                ),
                ("counted_views", models.IntegerField(default=0)),
                ("counted_likes", models.IntegerField(default=0)),
                ("status", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("available_seats", models.IntegerField(default=0)),
                (
                    "schedule",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 9, 20, 15, 31, 44, 704226)
                    ),
                ),
                ("category", models.ManyToManyField(to="course.category")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.trainer"
                    ),
                ),
            ],
            options={"ordering": ("-created_date",),},
        ),
        migrations.AddField(
            model_name="comment",
            name="which_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.courses"
            ),
        ),
    ]
