# Generated by Django 4.2.4 on 2023-09-14 22:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="schedule",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 14, 15, 30, 21, 30729)
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.trainer"
            ),
        ),
    ]
