# Generated by Django 4.2.4 on 2023-09-15 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_courses_image_alter_courses_schedule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="schedule",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 15, 8, 25, 32, 456862)
            ),
        ),
    ]
