# Generated by Django 4.2.4 on 2023-09-15 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_courses_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="schedule",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 15, 10, 17, 16, 272732)
            ),
        ),
    ]
