# Generated by Django 4.2.4 on 2023-09-16 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_alter_courses_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="schedule",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 16, 6, 34, 30, 449236)
            ),
        ),
    ]
