# Generated by Django 4.2.4 on 2023-09-17 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_alter_courses_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="schedule",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 16, 19, 54, 36, 653903)
            ),
        ),
    ]
