# Generated by Django 4.2.4 on 2023-09-17 03:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_alter_courses_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="schedule",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 16, 20, 19, 47, 133875)
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "which_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.courses"
                    ),
                ),
            ],
            options={"ordering": ["-created_date"],},
        ),
    ]
