# Generated by Django 4.2.4 on 2023-09-18 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0009_alter_courses_schedule_reply"),
    ]

    operations = [
        migrations.RemoveField(model_name="reply", name="email",),
        migrations.AlterField(
            model_name="courses",
            name="schedule",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 18, 8, 7, 17, 936384)
            ),
        ),
    ]
