# Generated by Django 4.2.4 on 2023-09-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0002_newsletter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=300)),
                ("message", models.TextField()),
            ],
        ),
    ]
