# Generated by Django 4.2.4 on 2023-08-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0003_rename_create_service_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="family",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=18, null=True),
        ),
    ]
