# Generated by Django 4.2.4 on 2023-08-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0004_service_family_service_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
