# Generated by Django 4.2.4 on 2023-08-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0005_service_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Marketing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="WebDevelopment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(name="service",),
    ]
